### ISSUE TITLE
filter original publication: add 'normal'

### ISSUE THREAD

**Issue by stefandrissen** [thomasheckmann/zxinfo-app#19]
While attempting to answer a question about which +3 games have additional content (https://spectrumcomputing.co.uk/forums/viewtopic.php?f=21&t=429). I started a search with machine type filtered by +3 (http://zxinfo.dk/search?machinetype=ZX-Spectrum%20128%20%2B3).

The filter on 'Original publication' then shows three choices:

- as part of a compilation
- on magazine covertape
- type-in

But I only want to see the 'normal' games. This could be achieved by adding 'normal' or by allowing the check box filters to be 'is' / 'is not'. The first option is probably easiest.

**Update 1:** it seems that 'not original publication = a part of a compilation' is not the same as 'not part of a compilation' - since a title that was also put on a compilation was originally not part of a compilation.

So... I'll leave it up to you. I'm assuming that the genretypes are not shown as filtering option since there are too many.

**Update 2:** looking it it again, I see entry genre on the /left/ hand option - but there can only select one. Something comparable to pricewatch on tweakers (https://tweakers.net/categorie/215/smartphones/producten/) could work nicely here - but would incur a major revamp of your ui :-)

**Comment by thomasheckmann** [comment]
1) Adding 'Normal' is easy, but should be left out on hardware and books

Left menu is only a "shortcut" for quick access - filtering should be used to narrow down search result, which is why it contains checkboxes for each option. As the same time it only shows options relevant for the search. Adding genre is easy, but UI wise it would be a mess.

**Comment by thomasheckmann** [comment]
Solution: All entries that are not a book, hardware or Compilation will have 'Standard' as default value for 'original publication'. "Standard" will be available in the filter options.
